<#
.SYNOPSIS
    Detection rule for {{APP_NAME}}
    Generated by Intune Packager — do not edit manually.

    Return codes:
      exit 0  = Application IS installed (Intune: compliant)
      exit 1  = Application is NOT installed (Intune: remediate)

.NOTES
    Version   : {{VERSION}}
    Generated : {{GENERATED_DATE}}
#>

$ErrorActionPreference = 'Stop'

try {
    {{DETECTION_SCRIPT}}
}
catch {
    Write-Output "Detection error: $_"
    exit 1
}
