<#
.SYNOPSIS
    Silent install script for {{APP_NAME}}
    Generated by Intune Packager — do not edit manually.

.NOTES
    Version   : {{VERSION}}
    Source    : {{SOURCE_URL}}
    Generated : {{GENERATED_DATE}}
#>

$ErrorActionPreference = 'Stop'
$LogPath = "$env:TEMP\{{SAFE_NAME}}_install.log"

function Write-Log {
    param([string]$Message)
    $ts = Get-Date -Format 'yyyy-MM-dd HH:mm:ss'
    "$ts  $Message" | Tee-Object -FilePath $LogPath -Append | Write-Host
}

try {
    Write-Log "Starting installation of {{APP_NAME}} {{VERSION}}"
    Write-Log "Installer: {{INSTALLER_FILE}}"

    $installerPath = Join-Path $PSScriptRoot "{{INSTALLER_FILE}}"

    if (-not (Test-Path $installerPath)) {
        throw "Installer not found: $installerPath"
    }

    Write-Log "Running: {{INSTALL_CMD}}"
    $proc = Start-Process -FilePath {{INSTALL_PROCESS}} -ArgumentList '{{INSTALL_ARGS}}' `
        -Wait -PassThru -NoNewWindow

    Write-Log "Exit code: $($proc.ExitCode)"

    # Acceptable exit codes: 0 = success, 3010 = reboot required, 1641 = reboot initiated
    $acceptableCodes = @(0, 3010, 1641)
    if ($proc.ExitCode -notin $acceptableCodes) {
        throw "Installation failed with exit code $($proc.ExitCode)"
    }

    Write-Log "Installation completed successfully"
    exit 0
}
catch {
    Write-Log "ERROR: $_"
    exit 1
}
