<#
.SYNOPSIS
    Silent uninstall script for {{APP_NAME}}
    Generated by Intune Packager — do not edit manually.

.NOTES
    Version   : {{VERSION}}
    Generated : {{GENERATED_DATE}}
#>

$ErrorActionPreference = 'Stop'
$LogPath = "$env:TEMP\{{SAFE_NAME}}_uninstall.log"

function Write-Log {
    param([string]$Message)
    $ts = Get-Date -Format 'yyyy-MM-dd HH:mm:ss'
    "$ts  $Message" | Tee-Object -FilePath $LogPath -Append | Write-Host
}

try {
    Write-Log "Starting uninstallation of {{APP_NAME}}"

    {{UNINSTALL_SCRIPT}}

    Write-Log "Uninstall command completed"
    exit 0
}
catch {
    Write-Log "ERROR: $_"
    exit 1
}
